apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: react-app-example
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31516
  selector:
    app: react-app-example
